import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import AuthProvider from "./AuthProvider";
import "react-toastify/dist/ReactToastify.css";
import { AuthContextProvider } from "./AuthContext";
const inter = Inter({ subsets: ["latin"] });
import Script from "next/script";
import NavBar from "@/components/Navbar/NavBar";
import AuthProvider from "./AuthProvider";
import TostifyProvider from "@/provider/TostifyProvider";
// import Script from 'next/script'
export const metadata: Metadata = {
  title: "EventsNow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <script src="https://www.payhere.lk/lib/payhere.js" defer /> */}
        <link rel="icon" href="/reusableComponents/nav-logo.png" sizes="any" />
        <AuthProvider>
          <AuthContextProvider>
            {/* <NavBar /> */}
            {children}
          </AuthContextProvider>
          <TostifyProvider />
        </AuthProvider>
      </body>
    </html>
  );
}
