import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../../../globals.css";
import "react-toastify/dist/ReactToastify.css";
// const inter = Inter({ subsets: ["latin"] });
import { ToastContainer } from "react-toastify";
import NavBar from "@/components/Navbar/NavBar";

export const metadata: Metadata = {
  title: "Organization dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <link
          rel="icon"
          href="/ReUsableComponentData/nav-logo.png"
          sizes="any"
        /> */}
        <NavBar />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
